def musicGenres()
    musicGenres = [
    "Acid Jazz",
    "Alternative Country",
    "Alternative Dance",
    "Alternative Metal",
    "Alternative Rock",
    "Ambient",
    "Americana",
    "Avant-Garde",
    "Bachata",
    "Ballad",
    "Big Band",
    "Bluegrass",
    "Blues",
    "Bolero",
    "Bossanova",
    "Bounce",
    "Breakbeat",
    "Britpop",
    "Bubblegum Pop",
    "Cajun",
    "Calypso",
    "Caribbean",
    "Celtic",
    "Chamber Music",
    "Chant",
    "Chillout",
    "Chiptune",
    "Christian",
    "Classic Rock",
    "Classical",
    "Club",
    "Conjunto",
    "Contemporary",
    "Cool Jazz",
    "Country",
    "Creole",
    "Crunk",
    "Cumbia",
    "Dance",
    "Dancehall",
    "Dark Ambient",
    "Death Metal",
    "Deathcore",
    "Deep House",
    "Delta Blues",
    "Detroit Techno",
    "Disco",
    "Doo Wop",
    "Doom Metal",
    "Downtempo",
    "Dream Pop",
    "Drone",
    "Drum and Bass",
    "Dub",
    "Dubstep",
    "East Coast Hip Hop",
    "Easy Listening",
    "EBM",
    "Electro",
    "Electronic",
    "Electronic Rock",
    "Electropop",
    "Emo",
    "Enka",
    "Ethnic",
    "Eurodance",
    "Experimental",
    "Fado",
    "Filk",
    "Flamenco",
    "Folk",
    "Folk Metal",
    "Folk Rock",
    "Funk",
    "Fusion",
    "Gangsta Rap",
    "Garage",
    "Glam",
    "Glitch",
    "Goa Trance",
    "Gospel",
    "Goth",
    "Grindcore",
    "Grunge",
    "Gypsy Jazz",
    "Hard Bop",
    "Hard House",
    "Hard Rock",
    "Hardcore",
    "Hardstyle",
    "Heavy Metal",
    "Hip Hop",
    "Honky Tonk",
    "House",
    "IDM",
    "Indie",
    "Indie Pop",
    "Indie Rock",
    "Industrial",
    "Instrumental",
    "Italo Disco",
    "J-Pop",
    "J-Rock",
    "Jazz",
    "Jazz Fusion",
    "Jazz Rap",
    "Jungle",
    "K-Pop",
    "Klezmer",
    "Krautrock",
    "Latin",
    "Latin Jazz",
    "Lounge",
    "Mambo",
    "Mariachi",
    "Math Rock",
    "Medieval",
    "Merengue",
    "Metal",
    "Metalcore",
    "Minimal",
    "Modern Classical",
    "Modular Synth",
    "Morna",
    "Motown",
    "Musette",
    "Music Hall",
    "Neo-Soul",
    "Neoclassical",
    "New Age",
    "New Jack Swing",
    "New Wave",
    "Noise",
    "Aggrotech",
    "Blackgaze",
    "Brutal Death Metal",
    "Chamber Pop",
    "Cinematic",
    "Cloud Rap",
    "Cybergrind",
    "Darkwave",
    "Death Industrial",
    "Digital Hardcore",
    "Doomcore",
    "Drill",
    "Dub Poetry",
    "Dub Techno",
    "Dungeon Synth",
    "Electro-Industrial",
    "Emocore",
    "Eurobeat",
    "Freak Folk",
    "Future Funk",
    "Gabber",
    "Garage Rock",
    "German Folk",
    "Gothic Metal",
    "Grime",
    "Groove Metal",
    "Gypsy Punk",
    "Happy Hardcore",
    "Hard Techno",
    "Harsh Noise",
    "Horror Punk",
    "IDM Ambient",
    "Indie Folk",
    "Industrial Metal",
    "Jazz Metal",
    "Jungle Terror",
    "Kawaii Metal",
    "Latin Metal",
    "Lo-Fi Hip Hop",
    "Madchester",
    "Mandopop",
    "Martial Industrial",
    "Mathcore",
    "Melodic Black Metal",
    "Melodic Death Metal",
    "Metalstep",
    "Microhouse",
    "Nerdcore",
    "Neurofunk",
    "New Orleans Jazz",
    "Nintendocore",
    "Nu Disco",
    "Nu Jazz",
    "Occult Rock",
    "Oi!",
    "Orchestral",
    "Pirate Metal",
    "Post-Bop",
    "Post-Industrial",
    "Post-Metal",
    "Post-Punk",
    "Post-Rock",
    "Progressive Metal",
    "Psychedelic",
    "Psychedelic Folk",
    "Psychedelic Rock",
    "Ragga",
    "Ragtime",
    "Rap Metal",
    "Riot Grrrl",
    "Rockabilly",
    "Samba",
    "Screamo",
    "Shibuya-Kei",
    "Shoegaze",
    "Ska Punk",
    "Slamming Brutal Death Metal",
    "Sludge Metal",
    "Smooth Jazz",
    "Soca",
    "Southern Rock",
    "Space Rock",
    "Speedcore",
    "Stoner Rock",
    "Symphonic Metal",
    "Synthwave",
    "Tango",
    "Technical Death Metal",
    "Thrash Metal",
    "Trance",
    "Trip Hop",
    "Tropical House",
    "Turbofolk",
    "UK Drill",
    "Vaporwave",
    "Viking Metal",
    "Witch House",
    "Yacht Rock"
  ] 
  return musicGenres
end

def themes
    themes = [
      "Unrequited love",
      "Heartbreak",
      "Longing",
      "Jealousy",
      "Betrayal",
      "Forgiveness",
      "Hope",
      "Despair",
      "Addiction",
      "Redemption",
      "Growing up",
      "Coming of age",
      "Mental health",
      "Loss",
      "Regret",
      "Revenge",
      "Isolation",
      "Overcoming fear",
      "Empowerment",
      "Ambition",
      "Self-discovery",
      "Self-acceptance",
      "Self-love",
      "Friendship",
      "Family",
      "Fate",
      "Destiny",
      "Identity",
      "Nostalgia",
      "Yearning",
      "Passion",
      "Temptation",
      "Seduction",
      "Obsession",
      "Deception",
      "Darkness",
      "Light",
      "Freedom",
      "Oppression",
      "Injustice",
      "Sorrow",
      "Joy",
      "Peace",
      "War",
      "Nature",
      "Spirituality",
      "Religion",
      "Philosophy",
      "Politics",
      "Technology",
      "Science",
      "History",
      "Culture",
      "Tradition",
      "Change",
      "Transformation",
      "Revolution",
      "Unity",
      "Diversity",
      "Equality",
      "Justice",
      "Love and friendship",
      "Sacrifice",
      "Betrayal",
      "Loyalty",
      "Passion and romance",
      "Grief",
      "Hope and faith",
      "Memory",
      "Repression",
      "Pain",
      "Recovery",
      "Addiction and recovery",
      "Empowerment",
      "Isolation and loneliness",
      "Mortality",
      "The human condition",
      "Death",
      "Existentialism",
      "Self-destruction",
      "The search for meaning",
      "Humanity",
      "Love and loss",
      "The beauty of life",
      "Betrayal and revenge",
      "The struggle for survival",
      "Human connection",
      "Desire and longing",
      "Faith and spirituality",
      "The power of nature",
      "The unknown",
      "The search for truth",
      "Happiness",
      "Success and failure",
      "The passage of time",
      "Change and transformation",
      "The road to redemption",
      "The journey of life",
      "The pursuit of happiness",
  ]
  return themes
end


def lyrics
    lyrics = [
    "I can't help falling in love with you, even though I know you'll never feel the same",
    "My heart is shattered into a million pieces, and I don't know if I can ever put it back together again",
    "Every night, I lie awake, dreaming of the day when you'll finally notice me",
    "The thought of you with someone else is tearing me apart, but I can't stop loving you",
    "You promised me forever, but you were just playing a game, and now I'm left with nothing",
    "I forgive you for what you've done, but I can't forget the pain you caused",
    "I'm holding onto hope that someday we'll be together again, but deep down I know it's just a fantasy",
    "I feel like I'm drowning in my own despair, and there's no way out",
    "I know I should let you go, but I can't seem to break free from your grasp",
    "I've been down this road before, but this time I'm determined to find my way back",
    "I'm trying to find myself in this world, but it feels like I'm always falling short",
    "Growing up is hard, but it's even harder when you don't know who you are",
    "I'm struggling with my mental health, and it feels like there's no one I can turn to",
    "I've lost someone I loved, and I don't know how to move on",
    "I wish I could turn back time and make things right, but it's too late now",
    "I'll make you pay for what you've done, and you'll regret ever crossing me",
    "I feel so alone in this world, like no one understands me or my pain",
    "I'm facing my fears head-on, and I won't let them control me anymore",
    "I'm taking back my power, and I won't let anyone take it away from me",
    "I'm on a journey of self-discovery, and I'm learning to love myself for who I am",
    "I'm not ashamed of who I am anymore, and I won't let anyone make me feel that way",
    "Friendship is a bond that can't be broken, and I'll always be there for you, no matter what",
    "Family is everything, and I'll always have their back, no matter what",
    "Sometimes I feel like my fate is already written, but I'm determined to change it",
    "Destiny is a fickle thing, and sometimes it's up to us to make our own",
    "I'm trying to find my identity in a world that wants to label me",
    "I miss the way things used to be, but I know I can't go back",
    "I'm yearning for something more, but I don't know what it is",
    "Passion is a fire that burns within me, and I won't let it die out",
    "I'm tempted by things that I know are bad for me, but I can't help myself",
    "You seduced me with your words, but now I see through your lies",
    "I'm obsessed with you, and I don't know how to break free from your hold",
    "You deceived me, and now I'm paying the price",
    "The darkness is consuming me, and I don't know if I'll ever find my way back to the light",
    "I loved you more than words could say, but you were blind to my affection.",
    "I gave you my heart, but you tore it apart and left me in pieces.",
    "I'm haunted by the memory of you, and the love that we once shared.",
    "I see you with her, and my heart aches with jealousy and regret.",
    "You promised me forever, but forever came and went without me.",
    "I forgive you for what you did, but I can never forget.",
    "I hold onto hope that one day we'll be together again.",
    "I'm drowning in despair, and I don't know how to get out.",
    "I thought I had control, but addiction had a hold on me.",
    "I've been down a long and rocky road, but I'm finally finding my way.",
    "Growing up is hard to do, but I'm learning who I am.",
    "I'm no longer a child, but I'm not quite an adult.",
    "My mind is a prison, and my thoughts are my captors.",
    "I lost the one I loved, and I don't know how to move on.",
    "If I could turn back time, I would never let you go.",
    "I'll get my revenge, and you'll regret what you did to me.",
    "I'm lost in my own world, and I can't seem to find my way out.",
    "I'm scared of the unknown, but I'm facing my fears head-on.",
    "I'm taking back my power, and I'm stronger than ever.",
    "I'm on a journey of self-discovery, and I'm learning to love who I am.",
    "I used to hate myself, but now I'm learning to accept me for me.",
    "I'm surrounded by friends who love me for who I am.",
    "My family means everything to me, and I'll do anything for them.",
    "I believe in fate, and I know that we were meant to be together.",
    "Destiny brought us together, and nothing can tear us apart.",
    "I'm searching for my identity, and I'm not sure who I am.",
    "I'm longing for the past, but I know I can't go back.",
    "My heart is yearning for you, but I know we can never be.",
    "Passion burns within me, and I can't resist your touch.",
    "Temptation is all around me, and I'm struggling to resist.",
    "Seduction is in your eyes, and I'm under your spell.",
    "I'm obsessed with you, and I can't break free from your hold.",
    "You deceived me, and I can't forgive you for what you did.",
    "The darkness surrounds me, and I'm struggling to find the light.",
    "I found the light within me, and now I'm shining brighter than ever.",
    "Freedom is what I long for, but oppression is what I feel.",
    "Injustice prevails, but I'll fight for what's right.",
    "My heart is heavy with sorrow, but I know I'll find joy again.",
    "I've found peace in my heart, and I'm spreading it to the world.",
    "War rages on, but love will conquer all.",
    "Nature is my sanctuary, and it heals my soul.",
    "Spirituality is what grounds me, and it gives me strength.",
    "I spit fire like a dragon, leaving haters in ashes.",
    "My rhymes are like a hurricane, tearing down all in its path.",
    "I'm the king of this game, bow down to the rap god.",
    "My flow is so sick, it should come with a warning label.",
    "I come from the streets, where survival is the only way.",
    "I've got a story to tell, and it's not for the faint of heart.",
    "I'm living proof that dreams can come true, with a little hard work.",
    "My words are weapons, and I'm not afraid to use them.",
    "I'm a lyrical assassin, taking out all the competition.",
    "I'm on a mission to change the world, one verse at a time.",
    "My rhymes are hotter than the sun, burning up the mic.",
    "I'm the voice of the voiceless, speaking truth to power.",
    "I've got bars for days, and I'm just getting started.",
    "My words are like bullets, piercing through the lies.",
    "I'm the underdog, but I'll come out on top.",
    "My flow is so sick, it could cure any disease.",
    "I'm the chosen one, destined for greatness.",
    "My rhymes are like a symphony, with each word as a note.",
    "I'm the real deal, and the haters can't deny it.",
    "I'm a rebel with a cause, fighting for what's right.",
    "My words are my weapon, and the pen is my sword.",
    "I'm a beast on the mic, and I'll never be tamed.",
    "My flow is untouchable, like a force field around me.",
    "I'm the king of this jungle, and I'll never be dethroned.",
    "My rhymes are like a storm, with thunder and lightning.",
    "I'm the real McCoy, and the fake ones can step aside.",
    "My words are my armor, protecting me from the hate.",
    "I'm a force to be reckoned with, and the game is mine.",
    "My flow is like a freight train, unstoppable and unyielding.",
    "I'm a warrior on the mic, and I'll never back down.",
    "My rhymes are like a hammer, smashing through the opposition.",
    "I'm the one and only, and the imitators can't keep up.",
    "My words are my legacy, and they'll live on forever.",
    "I'm a master of my craft, and the haters can't deny it.",
    "My flow is like a hurricane, destroying everything in its path.",
    "I'm a lyrical genius, and the game is my canvas.",
    "My rhymes are like a symphony, with each verse as a movement.",
    "I'm the real deal, and the rest are just posers.",
    "My words are my sword, cutting through the lies.",
    "I'm a champion of the game, and the throne is mine.",
    "My flow is like a volcano, erupting with pure fire.",
    "I'm a beast on the mic, and the haters can't touch me.",
    "My rhymes are like a weapon, with each line as a bullet.",
    "I'm the king of the hill, and the rest are just peasants.",
    "My words are my power, and they'll never be silenced.",
    "I'm a master of the game, and the world is my stage.",
  ]
  return lyrics
end